name: Build with MSVC 2019

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSVC 2019
      uses: microsoft/setup-msbuild@v1

    - name: Build project
      run: |
        msbuild /p:Configuration=Release /p:Platform=x86 maps_downloader.sln
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
          # Artifact name
          # A file, directory or wildcard pattern that describes what to upload
           path: "./Release/maps_downloader.exe;./Release/libcurl.dll;./Release/zlib1.dll"
          # The desired behavior if no files are found using the provided path.

           if-no-files-found: warn
